### ISSUE TITLE
現在のドキュメントとリポジトリのコンテンツの同期

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/openrtm.org#11]
現在、このリポジトリのドキュメントのテキストと、openrtm.org 上のドキュメントのテキストは同期されていない。

https://github.com/OpenRTM/openrtm.org/tree/master/Documents

以下に現在のopenrtm.orgのドキュメントの内容を反映させる。

**Comment by kkunita-work** [comment]
Issue resolved. Sync Work is completed.
