### ISSUE TITLE
rtm_project_jaの図が古いので、新しいのが必要

### ISSUE THREAD

**Issue by kkunita-work** [OpenRTM/openrtm.org#17]
**Describe the mistakes**
OpenRTMとは？　下の研究開発のページにあるhttps://openrtm.org/openrtm/sites/default/files/43/rtm_projects_ja.png
のファイルの情報が９年前で止まっているので、アップデートの必要があります。
新しい情報のファイルをください。

![rtm_projects_ja](https://user-images.githubusercontent.com/11814060/62989681-f3b17f80-be83-11e9-9052-304f2cd359ce.png)

**Comment by kkunita-work** [comment]
図だけなく、説明も古いです。修正お願いします。また現状の説明に２００７年からNEDO知能化プロジェクト　とありますが、図と一致しないので、図のアップデートとともに修正お願いします。

**Comment by n-ando** [comment]
ファイルをSlackで送りました。

**Comment by kkunita-work** [comment]
固有名詞が多く、英語化が難しいので質問を別Issueのところに追加しておきました。
PNGファイル化して(英語版はとりあえずの訳で)PRしました。

**Comment by n-ando** [comment]
このissueはどのPRに対応しますか？

**Comment by kkunita-work** [comment]
PR#39はずです。
