### ISSUE TITLE
UCROAのコンポーネント統合イメージ図の元ファイルを探して英語化

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/openrtm.org#18]
**Is your feature request related to a problem? Please describe.**
以下のコンポーネント統合イメージ図の元ファイルを探して英語化する。

![ucroa_ja](https://user-images.githubusercontent.com/11814060/62989776-67ec2300-be84-11e9-85e8-ff65033ed11a.png)

**Comment by n-ando** [comment]
産総研産業変革研究イニシアティブ のセクションは削除してください。
従って、図のアップデート・翻訳も不要です。

**Comment by kkunita-work** [comment]
セクション削除してPRしました。
