### ISSUE TITLE
プロジェクト名等　固有名詞の英語名は？

### ISSUE THREAD

**Issue by kkunita-work** [OpenRTM/openrtm.org#33]
次世代ロボット共通基盤開発
工業標準部　標準基盤研究
科振費　（これは科学振興調整費と同じですか？）
戦略的先端ロボット要素技術開発
瀬克支援ロボット実用化プロジェクト
ロボット大賞2xxx 優秀賞
知能化プロジェクト
科学振興調整費  
産総研産業変革研究イニシアティブ
ユーザー指向ロボットオープンアーキテクチャの開発
次世代ロボット知能化技術開発プロジェクト
基盤ロボット技術活用型オープンイノベーション促進プロジェクト
ロボットビジネス推進協議会
SICEシステムインテグレーション部門

Research and Development ページの作成に必要です。

**Comment by n-ando** [comment]
- 次世代ロボット共通基盤開発
  - Development of Common Platform Technology for Next-Generation Robots
- 工業標準部　標準基盤研究
  - AIST's Industrial Standards Department, Standard Infrastructure Research
- 戦略的先端ロボット要素技術開発
  - Strategic Advanced Robotic Elements Engineering Development Project
- 生活支援ロボット実用化プロジェクト
  - Practical Application of Personal Care Robot Project
- ロボット大賞2xxx 優秀賞
  - Outstanding performance award, the ROBOT AWARD 2007 
- 次世代ロボット知能化技術開発プロジェクト
  - 知能化プロジェクトも同じ
  - Intelligent RT Software Project
- 科学振興調整費
  - 科振費　（これは科学振興調整費と同じ）
  - Special Coordination Fund for Promoting Science and Technology
- 産総研産業変革研究イニシアティブ
  - AIST Industrial Transformation Research Initiative
- ユーザー指向ロボットオープンアーキテクチャ
  - User Centered Robot Open Architecture (UCROA)
- 基盤ロボット技術活用型オープンイノベーション促進プロジェクト
  - Fundamental Robot Technology-based Open Innovation Promotion Project
- ロボットビジネス推進協議会
  - Robot Business Promotion Council
- SICEシステムインテグレーション部門
  - SICE System Integration Division

**Comment by kkunita-work** [comment]
追加で、
* 分散コンポーネントシミュレータはDistributed component simulatorで良いですか？ちょっと違うような気もします
* 環境と作業構造のユニバーサルデザイン Universal design for a working environment and structure で良いですか？
* ロボット活用型市場化適用技術開発プロジェクト
* 福島県産学ロボット技術科初支援事業 (会津大学)
* 産学連携功労者表彰・経済産業大臣賞
もお願いします。

**Comment by n-ando** [comment]
- 分散コンポーネントシミュレータ
  - Distributed Component-based Robot Simulator
- 環境と作業構造のユニバーサルデザイン
  -  Universal-design for Environment and Manipulation Framework
- ロボット活用型市場化適用技術開発プロジェクト
  - Technology Development Project for Robot Commercialization Applications
- 福島県産学ロボット技術科初支援事業 (会津大学)
  - Fukushima Prefecture, Industry-University Robot Technology Development Support Project
- 産学連携功労者表彰・経済産業大臣賞
  - Industry-Academia-Government Collaboration Meritorious Person Award, METI Minister Awards

**Comment by kkunita-work** [comment]
セクション削除の結果必要なくなったものもありましたが、変更してPRしました。
