### ISSUE TITLE
OpenRTM-aistのインストール方法、インストーラの作業内容、インストールされるファイルの詳細をドキュメントに記載する

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/openrtm.org#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

OpenRTM-aist 1.1とインストーラの作業内容、インストールされるファイルが変わっているはずのため、以下のページに詳細を記載する。

- https://openrtm.org/openrtm/ja/node/6600

msiインストーラでインストールする場合、C++版、Python版、Java版、OpenRTPについて個別のモジュールでインストールされる内容について記載する。

またインストール方法について、GitHubのreleasesのスクリプトを今後も継続する場合はそのインストール手順を記載する。以前の一括インストールスクリプトに戻す場合は、インストールスクリプトの整備が完了次第手順を記載する。

**Describe alternatives you've considered**

**Additional context**

**Comment by n-kawauchi** [comment]
記載済みですので、このIssueは閉じます。
