### ISSUE TITLE
ドキュメントページの英語化（イントロ）

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/openrtm.org#9]
ドキュメントページ（イントロ）で英語化されていないものがあれば英語化する。
要点は2つ

- キャプチャ画像（RTSE等英語版を使用して）を英語化する。
- 本文はGoogle翻訳にかけて英語化されているものは段落ごとに文頭に(G)と記載されているので、英語の内容を確認する。

イントロのコンテンツは以下の通り

- https://openrtm.org/openrtm/en/doc/intro
- https://openrtm.org/openrtm/en/doc/whats-rtm
- https://openrtm.org/openrtm/en/doc/license
- https://openrtm.org/openrtm/en/doc/specification
- https://openrtm.org/openrtm/en/doc/about-rtc
- https://openrtm.org/openrtm/en/doc/rtc-devel-flow
- https://openrtm.org/openrtm/en/doc/rts-devel-flow
- https://openrtm.org/openrtm/en/doc/community

**Comment by kkunita-work** [comment]
イントロの部分はResearch and Developmentのページの固有名詞の英語の修正を除いて終わりました。安藤さんおIssueへの回答待ちです。
